// src/firebase/config.ts
// This file is automatically generated. Do not modify it manually.
import { FirebaseOptions } from 'firebase/app';

const firebaseConfig: FirebaseOptions = JSON.parse(
  process.env.NEXT_PUBLIC_FIREBASE_CONFIG || '{}'
);

export function getFirebaseConfig() {
  if (!firebaseConfig.apiKey) {
    throw new Error('Missing NEXT_PUBLIC_FIREBASE_CONFIG environment variable');
  }
  return firebaseConfig;
}
